### ISSUE TITLE
为什么要这么复杂，android不是可以用style吗

### ISSUE THREAD

**Issue by JonaNorman** [luxiaoming/ScoopsDemo#1]

**Comment by luxiaoming** [comment]
它有一些优势：
1这个就是对style的管理。你要设置某种主题，也是需要存储下当前设置的值的。
2再者它方便设置白天夜间模式，算是一个统一管理主题的方式。
3它可以使用注解方式，能让你代码量减少。
4算是让零散的style方式做一个封装。

这是用它的原因。
